language: android
before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
  # List and delete unnecessary components to free space
  - sdkmanager --list || true
  - sdkmanager --uninstall "extras;google;google_play_services"
  - sdkmanager --uninstall "extras;android;support"
  - sdkmanager --uninstall "platforms;android-10"
  - sdkmanager --uninstall "platforms;android-15"
  - sdkmanager --uninstall "platforms;android-16"
  - sdkmanager --uninstall "platforms;android-17"
  - sdkmanager --uninstall "platforms;android-18"
  - sdkmanager --uninstall "platforms;android-19"
  - sdkmanager --uninstall "platforms;android-20"
  - sdkmanager --uninstall "platforms;android-21"
  - sdkmanager --uninstall "build-tools;21.1.2"
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25" # Latest platform required by SDK tools
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
after_install:
  # Check components status
  - sdkmanager --list || true
script:
  - gradle build
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
      - android-sdk-license-.+
      - '.+'